/**
 * File: app/layout.tsx
 * Description: Root layout for the application.
 * Author: Noé Henchoz
 * Date: 2025-12-02
 * License: MIT
 */

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import { ScrollToTop } from '@/components/scroll-to-top'
import './globals.css'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

const paladins = localFont({
    src: '../public/fonts/paladins/paladins.ttf',
    variable: '--font-paladins',
})

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.variable,
                    paladins.variable,
                    'antialiased font-sans',
                )}
            >
                <ScrollToTop />
                {children}
                <Toaster />
            </body>
        </html>
    )
}
